public/*                            usr/share/kiwiwriters/htdocs
etc/kiwiwriters.conf.template       usr/share/kiwiwriters/etc
etc/kiwiwriters.cfg.template        usr/share/kiwiwriters/etc
db/*                                usr/share/kiwiwriters/db
lib/*                               usr/share/perl5
banners/*                           usr/share/kiwiwriters/banners
bin/kw-progress.pl                  usr/bin
bin/kw-fix-profile.pl               usr/bin
